import {
  Anchor,
  Button,
  H1,
  H3,
  H6,
  Paragraph,
  Separator,
  XStack,
  YStack,
  ScrollView,
  Sticker,
  Stack,
  Logo,
  H4,
} from '@my/ui'
import { Play } from '@tamagui/lucide-icons'
import { useLink } from 'solito/navigation'

export function HomeScreen({ pagesMode = false }: { pagesMode?: boolean }) {
  const linkProps = useLink({
    href: `/ar`,
  })

  return (
    <ScrollView f={1} jc="center" ai="center" gap="$8" p="$4" bg="$background">
      <XStack
        pos="absolute"
        w="100%"
        t="$6"
        gap="$6"
        jc="center"
        fw="wrap"
        $sm={{ pos: 'relative', t: 0 }}
      ></XStack>

      <YStack gap="$4">
        <Sticker alignSelf="center" width={'$10'} />
        <H1 ta="center" col="$color12">
          AR Face Tattoo
        </H1>

        <YStack maxWidth={600} gap={'$2'} paddingBottom={'$6'}>
          <H3 paddingBottom={'$4'} col="$color10" ta="center">
            An Augmented Reality Face Tattoo Previewer prototype developed by Ignacio Castro for
            CoCreate.
          </H3>

          <Separator />

          <YStack paddingTop={'$4'} gap={'$2'} paddingBottom={'$4'} alignItems="center">
            <H6 color={'$green11Light'} letterSpacing={0} textTransform="none" fontWeight={'$1'}>
              Give it a try! Ask for a face tattoo now!
            </H6>
            <Button
              borderRadius={'$12'}
              backgroundColor={'$green11'}
              width={'$6'}
              height={'$6'}
              icon={Play}
              size={'$5'}
              padding={0}
              {...linkProps}
            />
          </YStack>

          <Paragraph>
            This application allows for real-time previews on the face through augmented reality of
            images dynamically generated by artificial intelligence via voice commands, simulating
            facial tattoos. All images displayed are generated by artificial intelligence.
          </Paragraph>

          <Paragraph paddingBottom={'$4'}>It is compatible with Android, iOS, and Web.</Paragraph>
          <H4>Stack</H4>
          <Paragraph paddingBottom={'$4'}> Tamagui, Expo, Next</Paragraph>

          <H4>Features</H4>
          <Paragraph> Augmented Reality, Generative AI, Voice Recognizer, Web & Mobile</Paragraph>
        </YStack>
        <Separator />

        <XStack>
          <Paragraph flex={1} margin={'$0'} ta="center">
            Made with Love ♥️
          </Paragraph>
          <Stack justifyContent="center" flex={1}>
            <Logo />
          </Stack>
          <Paragraph flex={1} margin={'$0'} ta="center">
            Powered by AI 🤖
          </Paragraph>
        </XStack>
        <Separator />
      </YStack>
    </ScrollView>
  )
}
